[package]
name = "rustsdlretro-frontend"
version = "0.1.0"
edition = "2021"

[features]
default = ["minifb", "config", "null-audio"]
minifb = ["rustsdlretro-core/minifb"]
config = ["rustsdlretro-core/config"]
null-audio = ["rustsdlretro-core/null-audio"]
api = ["rustsdlretro-core/api"]

[dependencies]
rustsdlretro-core = { path = "../rustsdlretro-core", default-features = false, features = ["minifb", "config"] }
libc = "0.2"
