[package]
name = "rustsdlretro-core"
version = "0.1.0"
edition = "2021"

[features]
default = ["fbdev"]
fbdev = []
minifb = ["dep:minifb"]
config = ["dep:serde", "dep:serde_json"]
null-audio = []

[dependencies]
libc = "0.2"
evdev = "0.12"
alsa = "0.9"
zip = { version = "2", default-features = false, features = ["deflate"] }
minifb = { package = "minifb", version = "0.28", optional = true, features = ["x11"] }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }

[build-dependencies]
bindgen = "0.71"
cc = "1"
